### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by whplh** [TXH-mercury/VAST#11]
In the code I can find several licenses (Apache, BSD-3, MIT, ...)
Where/What is the license of this repository?
Cheers

**Comment by lihanddd** [comment]
Thank you for bringing this to our attention. We have now added a section to the README file that lists all the third-party licenses used in this repository. You can find the details in the [THIRD_PARTY_LICENSES.md](https://github.com/TXH-mercury/VAST/blob/master/THIRD_PARTY_LICENSES.md) file.

Additionally, we have clarified the licensing of our repository by including our own MIT License. You can find the full text of the license in the [LICENSE](https://github.com/TXH-mercury/VAST/blob/master/LICENSE) file.
