### ISSUE TITLE
Error about finetune_qa_msvd task (Miss key 'desc' or 'caption' in descs_qa_trainval.json)

### ISSUE THREAD

**Issue by BinzheLi95** [TXH-mercury/VAST#16]
03/26/2024 19:23:18 - INFO - __main__ -   load_from_pretrained: ./output/vast/pretrain_vast/ckpt/model_step_204994.pt
03/26/2024 19:23:18 - INFO - __main__ -   Load from pretrained dir ./output/vast/pretrain_vast
03/26/2024 19:23:19 - INFO - __main__ -   Unexpected keys ['vision_encoder.text.logit_scale']
03/26/2024 19:23:19 - INFO - __main__ -   missing_keys  ['vision_encoder.logit_scale']
03/26/2024 19:23:20 - INFO - __main__ -   ==================learning_rate_settings==================

03/26/2024 19:23:20 - INFO - __main__ -     basic_lr : 1e-05
03/26/2024 19:23:20 - INFO - __main__ -     clip_lr_visual : 5e-07
03/26/2024 19:23:20 - INFO - __main__ -     clip_lr_visual_len : 245
03/26/2024 19:23:20 - INFO - __main__ -     new_lr : 0
03/26/2024 19:23:20 - INFO - __main__ -     new_params_name: []
  0%|                                                                                                                            | 0/5670 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/mnt/workspace/Project/VideoLargeModel/VAST/./run.py", line 63, in <module>
    main()
  File "/mnt/workspace/Project/VideoLargeModel/VAST/./run.py", line 46, in main
    train(model, optimizer, train_loader, val_loaders, args.run_cfg, start_step = start_step, verbose_time=False)
  File "/mnt/workspace/Project/VideoLargeModel/VAST/utils/pipeline.py", line 35, in train
    for step, (name, batch) in enumerate(train_loader):
  File "/mnt/workspace/Project/VideoLargeModel/VAST/data/loader.py", line 101, in __iter__
    self.preload(loader_it)
  File "/mnt/workspace/Project/VideoLargeModel/VAST/data/loader.py", line 112, in preload
    self.batch = next(it)
  File "/mnt/workspace/Project/VideoLargeModel/VAST/data/loader.py", line 48, in __iter__
    batch = next(iter_)
  File "/home/pai/envs/vast/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
  File "/home/pai/envs/vast/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/home/pai/envs/vast/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/home/pai/envs/vast/lib/python3.9/site-packages/torch/_utils.py", line 644, in reraise
    raise exception
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/pai/envs/vast/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/pai/envs/vast/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/pai/envs/vast/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/mnt/workspace/Project/VideoLargeModel/VAST/data/IndexAnno.py", line 69, in __getitem__
    raw_captions = anno['desc'] if 'desc' in anno else anno['caption']
KeyError: 'caption'

I am trying the VQA task on MSVD-QA dataset.
I use the "python3 -m torch.distributed.launch \
--nnodes 1 \
--node_rank 0 \
--nproc_per_node 4 \
--master_port 9834 \
./run.py \
--learning_rate 1e-5 \
--checkpointing true \
--first_eval false \
--config ./config/vast/finetune_cfg/VQA-msvd.json \
--pretrain_dir $output_dir \
--save_best true \
--output_dir $output_dir/downstream/VQA-msvd \" command line and meet above error.

I notice the AnnoIndexedDataset(Dataset) require 'desc' or 'caption' in anno, but the msvd/descs_cap_train.json do not have these info. I want to ask how to fix thie error. Thank you.

**Comment by BinzheLi95** [comment]
I solve the problem by modifying the line 70 in IndexAnno.py
From         raw_captions = anno['desc'] if 'desc' in anno else anno['caption']  
to
if 'desc' in anno or 'caption' in anno :
    raw_captions = anno['desc'] if 'desc' in anno else anno['caption']
else 
    raw_captions = " "

**Comment by wonzin** [comment]
Hi, is your solution returns the right result? I am curious to leave the raw_captions empty is a visible solution or not

**Comment by BinzheLi95** [comment]
> Hi, is your solution returns the right result? I am curious to leave the raw_captions empty is a visible solution or not

Yes, I obtain the right QA result.  Setting raw_captions = " "  for QA task is ok because the raw_captions  is not necessary for QA task.

**Comment by wonzin** [comment]
Thank you for your reply :)  It really helps me!

**Comment by wonzin** [comment]
Hi, Did you try "Testing" ?
I think your way of doing is not a solution.

Check this
**vast/model/vast.py**

   def forward_qa(self, batch, task, compute_loss=True):
        subtasks = task.split('%')[1:]
        raw_questions = batch.raw_questions
        raw_answers = batch.raw_answers
      
        if isinstance(raw_questions[0],list): #### test
            # raw_batch_size = len(raw_questions)
            num_questions = [len(i) for i in raw_questions]
            raw_questions = [j for d in raw_questions for j in d]

        question_tokens = self.multimodal_encoder.tokenizer(raw_questions,
                                                            padding="max_length",
                                                            truncation=True,
                                                            max_length=self.max_caption_len,
                                                            return_tensors="pt").to(torch.device('cuda'))

        question_tokens_ids, question_tokens_mask = question_tokens.input_ids, question_tokens.attention_mask
        
"raw_questions" is used.
